version: "3.9"

services:
  backend:
    container_name: backend_chat
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./package.json:/app/package.json
      - ./backend:/app
    image: node
    ports:
      - "5005:5005"
    environment:
      - PG_DB=chat_app_db
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_HOST=postgres
    depends_on:
      - postgres

  postgres:
    container_name: postgres_chat
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=chat_app_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    user: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}