version: "3.9"

services:
  backend:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./package.json:/app/package.json
      - ./backend:/app
    image: node
    ports:
      - "5005:5005"
    environment:
      - PG_DB=chat_app_db
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_HOST=postgres
    depends_on:
      - postgres
    networks: 
      - node-network
    tty: true
  
  frontend:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    tty: true
    networks: 
      - node-network

  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=chat_app_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    user: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks: 
      - node-network

  nginx:
    depends_on:
      - backend
      - frontend
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3051:80"
    networks: 
      - node-network

volumes:
  postgres_data: {}

networks: 
  node-network:
    driver: bridge