# Step 2: Set up the production environment
# FROM nginx:stable-alpine
# COPY /build /usr/share/nginx/html
# COPY /sounds /usr/share/nginx/html/assets/sounds
# COPY ./default.conf /etc/nginx/conf.d/default.conf
# COPY ./certs /etc/nginx/ssl
FROM nginx
COPY ./default.conf /etc/nginx/conf.d/default.conf
